spring.application.name=vizja-xd-backend
spring.datasource.url=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v1

#for handling non-existent routes exceptions
spring.mvc.problemdetails.enabled=false

#tokens
app.access-token.secret=qwertyuiopasdfghjklzxcvbnm1234567890qwertyuiopasdfghjklzxcvbnm1234567890
#600,000 = 10min
app.access-token.expiration-ms=6000000
#86,400,000 = 24h
app.refresh-token.expiration-ms=86400000
logging.level.root=DEBUG
