spring.application.name=vizja-xd-backend

# H2 file-based database
spring.datasource.url=jdbc:h2:file:./data/socialapp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v1

spring.mvc.problemdetails.enabled=false

app.access-token.secret=qwertyuiopasdfghjklzxcvbnm1234567890qwertyuiopasdfghjklzxcvbnm1234567890
app.access-token.expiration-ms=6000000
app.refresh-token.expiration-ms=86400000
logging.level.root=DEBUG
